spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 
  jpa:
    hibernate:
      ddl-auto: update
