server:
  port: 8181
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rashidRizvi98/cloud-config-store
          search-paths:
            - '*service'
          default-label: master
  application:
    name: local-config

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
