spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_service_db?createDatabaseIfNotExist=true
    username: root
    password: *****
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: project-service
server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost