spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_service_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
       resourceserver:
         jwt:
           issuer-uri: http://localhost:8080/auth/realms/employee-management-realm

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: department-service
server:
  port: 8085

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost